Uso de GitHub Artifacts para guardar el tfstate y permitie el Terraform destoy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,7 +12,7 @@ on:
           - apply
           - destroy
       tfstate_file:
-        description: 'Path to terraform.tfstate zip for destroy'
+        description: 'Terraform state file for destroy'
         required: false
         
 jobs:
@@ -82,14 +82,25 @@ jobs:
         name: terraform-state
         path: ./terraform.tfstate
         
-    - name: Download Terraform State
-      if: ${{ github.event.inputs.action == 'destroy' }}
-      uses: actions/download-artifact@v4
-      with:
-        name: terraform-state
-        path: ./terraform.tfstate  
+    # - name: Download Terraform State
+      # if: ${{ github.event.inputs.action == 'destroy' }}
+      # uses: actions/download-artifact@v4
+      # with:
+        # name: terraform-state
+        # path: ./terraform.tfstate  
       
-
+    - name: Prepare Terraform state for destroy
+      if: ${{ github.event.inputs.action == 'destroy' }}
+      run: |
+        if [ -z "${{ github.event.inputs.tfstate_file }}" ]; then
+          echo "ERROR: No tfstate file uploaded for destroy"
+          exit 1
+        fi
+        mkdir -p ./terraform
+        cp "${{ github.event.inputs.tfstate_file }}" ./terraform/terraform.tfstate
+        echo "Terraform state prepared:"
+        ls -la ./terraform
+        
     - name: Terraform Destroy
       if: ${{ github.event.inputs.action == 'destroy' }}
       run: |
